name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Format check
        run: npm run format:check
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm test --coverage
      - name: Commit build
        uses: endbug/add-and-commit@v9
        with:
          add: 'build --force'
          force: true
          message: Add build code
          ref: v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
